[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "mpl-tools==0.4.0",
    "numpy>=2.3.3",
    "vpython==7.6.5",
]
